config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to:'pages#about'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum:6, maximum:100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles
  validates :username, presence: true, 
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
    uniqueness: { case_sensitive: false }, 
    length: { maximum: 105 }, 
    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def show
      # byebug
    end
  
    def index
      @article = Article.all
    end
  
    def new
      @article = Article.new
    end
  
    def create
      @article = Article.new(article_params)
      @article.user = User.first
      if @article.save
        flash[:notice]="Article was created sucessfully."
        redirect_to @article
      else
        render :new
      end
    end
  
    def update
      if @article.update(article_params)
        flash[:notice]="Article was Updated Sucessfully."
        redirect_to @article
      else
        render 'edit'
      end
    end
  
    def edit
    end
  
    def destroy
      @article.destroy
      redirect_to articles_path
    end
  
    private
  
    def set_article
      @article = Article.find(params[:id])
    end
  
    def article_params
      params.require(:article).permit(:title, :description)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
  
    end
  
    def about
  
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully submitted"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    private 
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
  <div class="col-10">
       <%= render 'shared/errors', obj: @article %>

      <%= form_with(model: @article,class: "shadow p-3 mb-3 bg-info rounded", local: true, data: { turbo: false }) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %>
            <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="form-group row">
            <%= f.label :description, class: "col-2 col-form-label" %>
              <div class="col-10">

              <%= f.text_area :description,rows: 10, class: "form-control" %>
            </div>
          </div> 

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
  </div>
  <%= link_to '[Cancel and return to articles listing]', articles_path%>
  </div>
          </div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<div class="card text-center">
<div class="container">
<% for article in @article %>
    <div class="row  justify-content-md-center" >
        <div class="col-8 mt-4">
       by <%= article.user.username if article.user %>
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title"><%=  link_to article.title, article_path(article), class: "text-success" %></h5>
    <p class="card-text"><%= truncate(article.description, length: 100) %>.</p>
    <a href="#" class="btn btn-outline-success">View</a>
    <a href="#" class="btn btn-outline-info">Edit</a>
    <a href="#" class="btn btn-outline-danger">Delete</a>

  </div>
  <div class="card-footer text-muted">
  <small> Created <%= time_ago_in_words(article.created_at) %> age,
  edited <%= article.updated_at %> age </small>
  </div>
    </div>
        </div>
        </div>

<% end %>
</div>

<table>
<thead>
<tr>
<th>Title</th>
<th>Description</th>
<th colspan="3">Action</th>

</tr>
</thead>

<tbody>
<% for article in @article %>
<tr>
<td><%=article.title %></td>
<td><%=article.description %></td>
<td><%= link_to 'Show', article_path(article) %></td>
<td><%= link_to 'Edit', edit_article_path(article) %></td>
<td><%= link_to 'Delete', article_path(article),data:{ turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>

</tr>
<% end %>
</tbody>
</table>
<p>
<%= link_to 'Create new article',new_article_path %>
</p>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Article Details</h1>
       by <%= @article.user.username if @article.user %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Delete', article_path(@article),data:{ turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
  <%=msg %>
  <% end %>

app/views/layouts/_navigation.html.erb
  
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studentproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
   
      <%=render 'layouts/navigation' %>
      <%=render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 style="color: red">this is the about page</h1>
<%= link_to 'Artical listing', articles_path %> | 
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div style="flex:1 0 auto;background-color:lightgrey;">
<div class="container" style="margin-top: 25px;">
    <div class="jumbotron text-center"  style="background-image: asset-url('/home/suren/Desktop/cloco/studentproject/app/assets/images/nature.avif')";>
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </p>
    </div>
</div>

</div>
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small> Copyright &copy; Your Website</small>
    </div>
    </footer>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented <%= obj.class.name.downcase %></h4>
        <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul> 

     <%
=begin%>
 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button> 
<%
=end%>
</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
  <div class="col-10">
<%= render 'shared/errors', obj: @user %>

      <%= form_with(model: @user,class: "shadow p-3 mb-3 bg-info rounded", local: true, data: { turbo: false }) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label" %>
            <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label" %>
              <div class="col-10">

              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div> 

            <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label" %>
              <div class="col-10">

              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div> 

        <div class="form-group row justify-content-center">
          <%= f.submit "Signup", class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
  </div>
  <%= link_to '[Cancel and return to articles listing]', articles_path%>
  </div>
          </div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha blog</h1>
<%= render 'form' %>